services:
- redis-server
sudo: false
language: php
php:
- 7.2
- 7.1
- 7.0
- 5.6
- 5.5
install:
- composer install
script: |
    set -xe
    find . -name '*.php' | grep -v './vendor/' | xargs -I{} php -l "{}" \;
    ant test
notifications:
  hipchat:
    rooms:
      secure: XVGvIN4wW6po+uYi7G3jip5e7Jo5um/eEz7GDNxkNGfKuMhaq1NF/U14ngOK38zM20MLXDForSb6HDJhdDScLdVV42EWZmb0bYp58uy1+dvQTzDzmnKzugw4UKpPhr6932msiB+T5/Ss5iEd/A4RaRsHBC8jgRVNKLnZ5rcb3ao=
env:
  global:
  - PERSONA_TEST_HOST: https://staging-users.talis.com
  - secure: P6xLcE2Iy4OS47ZS4v2I3C7LUsXMH8vYiJ+B3lX/KCWF5xunHYfj+mbVlMXRyyPANP0SZgIwaobSvyP2+xpv7MTSo9TWMYNR6WaLcF65QlU/rnnl2UBTrBGQI7jAUeLqPpG2xB9ZkCoR+6r53uKRwbgOVA88ibp8iXAao0LQ7d2Cf40ddyGsaoauQg3heVT/V9KwXmf6mvbVSYMLatY4SN8ElZRy5cFF843JKX+7RMs8Zb7o2hTHoE3rFvsqhnb0zCUjo3iwVsUWI/C+yySSxiwzw1vBaR6uEe7Kkr2FxICh8avRJjP7qpM3jiyKmX/PG7mBfqOtWjyRoA7jgEa+hFksXGL4U6656wx9SMFY8NvvxZ42M7EdUfwGM7XDj4vcSP2JK+AY0wdUOjxVstIiHrcIJE4WZ8DVg1hiqAvmT6V1WpEpQ8Ph/FgdLAL9ZtkTsxFfJFve0kaAOQXfY13CgXHeGUZTtzVKZKyBzRy/MzewJUqWXtzEuRIhyLwEIsIqr7leXpf5p7iw355luV9junLcED9zlJQDL1dZ4/CjE7317FkqgR0saCaCuh0Ujjgm3+hXg/a0VT09HddU5NnlgYwmZreNB9y1FpLzzWOXjvxrllJjjBrfarhcO166rsoGyaHMFJWgXXBBaHHLlnvuTVoDlmaR7IMFynA9U9G93LU=
  - secure: fgeHTrQLww8MJKY6di9y8bDu/xdNJmvC0aTN3Kz3Uu/y/96RvnFd+b11UBd2AGzaNjKGCXSs5GlZPWd9tq4z2waCQ1CPEOlZOLDgXu/alQcngyu7DOPGBoHgFlbnMZGatTnvaD56e04pu+fp7CLcjRXQOQbTWbietb2VotIVIxJB/sne1ycaqhBeBhXOWs3i9M7vq6XGjHp658MuW9fDo/b3UHf9DAJku6yFjjGOFE6dEsNb1cYaoTxi0j/ELnoVXEUXmZTW1ZcFDQXIA4gWH93BQqC4oMHwj30otUWoItVIUZq9OyaaTGH3pBlW/doOwpvtVXoheNpRyWdLlqz5do7vbY5EpWPm1Is68Y5eKbrawfhRE+T+OSTGaPDW9wl77pxU7PzLrq4ZhH4P5g+K2HAdaEAiSMugtQrx5tmLq4UwHDzgB8RN3ZHaqC5AgqL+x1hQG7YTz+EJENGOTVhOZLhUZJFQC0flLY5WJIjZMTZL9UWq6h41d7x/xUk0njpptRBFKBH4sg9t0T/lbXpDheOV5mV1eyLYuSDczjhs7HsrvSWaKSU0pE9LVdlLMPFK0QdiPUjIxp5nmG3fQjBuhiCKpN38ZcPzEoA4g45SfAdkeh9hjB2g0xn2UcXMQV+ILnNKhuZUmMJ9DECT6BVCdV3svVfm+ZRbDAjfZzuSYvo=
