version: '2'

services:
  lint:
    image: talis/talis-php
    volumes:
      - "./src:/var/talis-php/src"
      - "./test:/var/talis-php/test"
      - "./build.xml:/var/talis-php/build.xml"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant lint"
  codecheck:
    image: talis/talis-php
    volumes:
      - "./src:/var/talis-php/src"
      - "./test:/var/talis-php/test"
      - "./build.xml:/var/talis-php/build.xml"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant code-check"
  test:
    image: talis/talis-php
    volumes:
      - "./src:/var/talis-php/src"
      - "./test:/var/talis-php/test"
      - "./build.xml:/var/talis-php/build.xml"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant test"
  unittest:
    image: talis/talis-php
    volumes:
      - "./src:/var/talis-php/src"
      - "./test:/var/talis-php/test"
      - "./build.xml:/var/talis-php/build.xml"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant unittest"
  integrationtest:
    image: talis/talis-php
    volumes:
      - "./src:/var/talis-php/src"
      - "./test:/var/talis-php/test"
      - "./build.xml:/var/talis-php/build.xml"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant integrationtest"
