version: "3.7"

x-common-values: &common-values
  image: talis/talis-php
  network_mode: host
  build:
    context: .
    network: host
  environment:
    PERSONA_TEST_HOST: ${PERSONA_TEST_HOST:-http://persona.talis.local}
    PERSONA_TEST_OAUTH_CLIENT: ${PERSONA_TEST_OAUTH_CLIENT:-primate}
    PERSONA_TEST_OAUTH_SECRET: ${PERSONA_TEST_OAUTH_SECRET:-bananas}
  volumes:
    - ".:/var/talis-php"

services:
  init:
    <<: *common-values
    command: "bash -c 'test -f composer.phar || (curl -sS https://getcomposer.org/installer | php); php composer.phar install'"

  lint:
    <<: *common-values
    command: "php composer.phar lint"

  code-check:
    <<: *common-values
    command: "php composer.phar code-check"

  test:
    <<: *common-values
    command: "php composer.phar test"

  unittest:
    <<: *common-values
    command: "php composer.phar unittest"

  integrationtest:
    <<: *common-values
    command: "php composer.phar integrationtest"

  local-dev:
    <<: *common-values
    command: "/bin/bash"

  coverage:
    <<: *common-values
    command: "php composer.phar coverage"

  analyse:
    image: phpstan/phpstan:0.12.40
    volumes:
      - ".:/var/talis-php"
    working_dir: /var/talis-php
    command: "analyse src"
