version: '2'

services:
  init:
    image: talis/talis-php
    volumes:
      - ".:/var/talis-php"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant init"
  lint:
    image: talis/talis-php
    volumes:
      - ".:/var/talis-php"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant lint"
  lint-stan:
    image: phpstan/phpstan
    volumes:
      - ".:/app"
    command: 'analyse /app'
  codecheck:
    image: talis/talis-php
    volumes:
      - ".:/var/talis-php"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant code-check"
  test:
    image: talis/talis-php
    volumes:
      - ".:/var/talis-php"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant test"
  unittest:
    image: talis/talis-php
    volumes:
      - ".:/var/talis-php"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant unittest"
  integrationtest:
    image: talis/talis-php
    volumes:
      - ".:/var/talis-php"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant integrationtest"
  coverage:
    image: talis/talis-php
    volumes:
      - ".:/var/talis-php"
    command: /bin/bash -c "service redis-server start && source /etc/profile.d/* && ant coverage"
