version: '2'

services:
  test:
    image: talis/talis-php
    volumes:
      - "./src:/var/talis-php/src"
      - "./test:/var/talis-php/test"
      - "./build.xml:/var/talis-php/build.xml"
  unittest:
    image: talis/talis-php
    volumes:
      - "./src:/var/talis-php/src"
      - "./test:/var/talis-php/test"
      - "./build.xml:/var/talis-php/build.xml"
    command: /bin/bash -c "service redis-server start && ant unittest"
  integrationtest:
    image: talis/talis-php
    volumes:
      - "./src:/var/talis-php/src"
      - "./test:/var/talis-php/test"
      - "./build.xml:/var/talis-php/build.xml"
    command: /bin/bash -c "service redis-server start && ant integrationtest"
