version: "3.7"

x-common-values: &common-values
  image: talis/talis-php
  network_mode: host
  build:
    context: .
    network: host
  environment:
    PERSONA_TEST_HOST: ${PERSONA_TEST_HOST:-http://persona.talis.local}
    PERSONA_TEST_OAUTH_CLIENT: ${PERSONA_OAUTH_CLIENT:?required}
    PERSONA_TEST_OAUTH_SECRET: ${PERSONA_OAUTH_SECRET:?required}
  volumes:
    - ".:/var/talis-php"

services:
  init:
    <<: *common-values
    command: "ant init"

  lint:
    <<: *common-values
    command: "ant lint"

  code-check:
    <<: *common-values
    command: "ant code-check"

  test:
    <<: *common-values
    command: "ant test"

  unittest:
    <<: *common-values
    command: "ant unittest"

  integrationtest:
    <<: *common-values
    command: "ant integrationtest"

  local-dev:
    <<: *common-values
    command: "/bin/bash"

  coverage:
    <<: *common-values
    command: "ant coverage"

  analyse:
    image: phpstan/phpstan:0.12.40
    volumes:
      - ".:/var/talis-php"
    working_dir: /var/talis-php
    command: "analyse src"
