x-common-env: &common-env
  PERSONA_TEST_HOST: ${PERSONA_TEST_HOST:-http://persona.talis.local}
  PERSONA_TEST_OAUTH_CLIENT: ${PERSONA_TEST_OAUTH_CLIENT:-primate}
  PERSONA_TEST_OAUTH_SECRET: ${PERSONA_TEST_OAUTH_SECRET:-bananas}

x-common-values: &common-values
  image: talis/talis-php
  network_mode: host
  build:
    context: .
    network: host
  environment: *common-env
  volumes:
    - ".:/var/talis-php"

services:
  init:
    <<: *common-values
    command: "composer install"

  lint:
    <<: *common-values
    command: "composer lint"

  code-check:
    <<: *common-values
    command: "composer code-check"

  test:
    <<: *common-values
    command: "composer test"

  unittest:
    <<: *common-values
    command: "composer unittest"

  integrationtest:
    <<: *common-values
    command: "composer integrationtest"

  local-dev:
    <<: *common-values
    command: "/bin/bash"

  coverage:
    <<: *common-values
    environment:
      <<: *common-env
      XDEBUG_MODE: coverage
    command: "composer coverage"

  analyse:
    image: phpstan/phpstan:0.12.40
    volumes:
      - ".:/var/talis-php"
    working_dir: /var/talis-php
    command: "analyse src"
